=== olpa/templating-for-api/tplfa/schemas/request.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "TplfaRequest",
  "title": "TplfaRequest",
  "$ref": "#/definitions/TplfaRequest",
  "definitions": {
    "TplfaRequest": {
      "type": "object",
      "required": ["url", "body", "method"],
      "properties": {
        "url": { "type": "string" },
        "method": { "type": "string" },
        "body": { "type": "object" },
        "headers": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "browsingTopics": { "type": "boolean"},
        "keepalive": {"type": "boolean"}
      },
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== olpa/templating-for-api/apis/mistral/fixture/request.json
{
   "body": {
      "messages": [
         {
            "content": "hello",
            "role": "user"
         }
      ],
      "model": "mistral-large-latest"
   },
   "headers": {
      "Authorization": "Bearer test-token",
      "Content-type": "application/json"
   },
   "method": "POST",
   "url": "https://api.mistral.ai/v1/chat/completions"
}
